[package]
name = "recrust"
# Convention: major/minor is equal to rec's major/minor
version = "5.3.0"
edition = "2021"

[lib]
name = "recrust"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { package = "serde_yml", version = "0.0.12" }
ipnet = "2.8"
once_cell = "1.18.0"
base64 = "0.22"
hyper = { version = "1", features = ["server", "http1"]}
tokio = { version = "1" , features = ["rt", "net"]}
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["tokio"]}
bytes = "1.8"
form_urlencoded = "1.2"
hyper-rustls = { version = "0.27",  default-features = false }
rustls = { version = "0.23", default-features = false, features = [] }
rustls-pemfile = "2.2"
pki-types = { package = "rustls-pki-types", version = "1.10" }
tokio-rustls = { version = "0.26", default-features = false }
uuid = { version = "1.12.1", features = ["v4"] }

[build-dependencies]
cxx-build = "1.0"

