sudo: required
dist: trusty
group: edge
before_script:
 - git describe --always --dirty=+
 - sudo apt-get update -qq
 - sudo apt-get install --quiet --quiet --no-install-recommends
     moreutils
     pandoc
     python-virtualenv
     xmlto
 - virtualenv $HOME/.venv
 - source $HOME/.venv/bin/activate
 - pip install pandocfilters==1.2.3 mkdocs==0.14 linkchecker==9.3 click==5.1 requests==2.9.2
 - deactivate
script:
 - ./bootstrap
#Build without --enable-botan1.10 option, Botan/SoftHSM conflict #2496
 - source $HOME/.venv/bin/activate
 - ./configure
 - cd docs
 - make check-links
 - deactivate
 - cd ..
 - git status
 - git status | grep -q clean
notifications:
  irc:
    channels:
      - "irc.oftc.net#powerdns-dev"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
