language: cpp
compiler:
  - gcc
  - clang
before_script:
 - git describe --always --dirty=+
 - sudo /sbin/ip addr add 10.0.3.0/24 dev lo
 - sudo rm /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
 - sudo apt-get update
 - sudo apt-get install --no-install-recommends libboost-all-dev libtolua-dev bc libcdb-dev libnet-dns-perl unbound-host ldnsutils dnsutils bind9utils libtool libcdb-dev xmlto links asciidoc ruby-json ruby-sqlite3 rubygems libcurl4-openssl-dev ruby1.9.1 socat time libzmq1 libzmq-dev pkg-config daemontools authbind liblua5.1-posix1 libopendbx1-dev libopendbx1-sqlite3 python-virtualenv libldap2-dev bind9
 - sudo ln -sf /dev/urandom /dev/random
script:
 - ./bootstrap
 - ./configure --with-modules='bind' --enable-unit-tests --enable-tools
 - make -j 4
 - make -j 4 check
 - make -j 4 oneshot
 - sudo mkdir -p /usr/local/lib
 - sudo cp ext/libldns* /usr/local/lib
 - sudo ldconfig
 - PATH=$(pwd)/ext:$PATH ./runtests
 - cd ../regression-tests.nobackend/
 - ./runtests
 - test ! -s ./failed_tests
notifications:
  irc:
    channels:
      - "irc.oftc.net#powerdns-dev"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
