sudo: required
dist: trusty
group: edge
language: cpp
compiler:
  - gcc
  - clang
env:
  - PDNS_BUILD_PRODUCT=recursor

matrix:
  exclude:
    - compiler: clang
      env: PDNS_BUILD_PRODUCT=docs

before_script:
  - git describe --always --dirty=+

  ### setup travis environment ###
  - sudo sysctl net.ipv6.conf.lo.disable_ipv6=0
  - export POSIXLY_CORRECT=1
  - export CFLAGS=-O0
  - export CXXFLAGS=-O0
  - export OPTFLAGS=-O0
  - sudo apt-get -qq update

script:
  - ./build-scripts/travis.sh

notifications:
  irc:
    channels:
      - "irc.oftc.net#powerdns-dev"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
