sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang

before_script:
  - git describe --always --dirty=+

  ### setup travis environment ###
  - sudo sysctl net.ipv6.conf.lo.disable_ipv6=0
  - export POSIXLY_CORRECT=1
  - export CFLAGS=-O0
  - export CXXFLAGS=-O0
  - export OPTFLAGS=-O0
  - sudo apt-get -qq update


  # ldap-backend
  - sudo apt-get -qq --no-install-recommends install
    libldap-dev

  # authoritative test requirements / setup
  - sudo apt-get -qq --no-install-recommends install
    bind9utils
    ldnsutils
    libnet-dns-perl
    moreutils
    unbound-host
    validns
    default-jre
    jq
  - cd ..
  - wget http://www.verisignlabs.com/dnssec-tools/packages/jdnssec-tools-0.12.tar.gz
  - sudo tar xfz jdnssec-tools-0.12.tar.gz --strip-components=1 -C /
  - cd pdns

script:
  - set
  - sudo apt-get -qq --no-install-recommends install slapd ldap-utils
  - mkdir /tmp/ldap-dns
  - pushd /tmp/ldap-dns
  - for schema in /etc/ldap/schema/{core,cosine}.schema ${TRAVIS_BUILD_DIR}/modules/ldapbackend/{dnsdomain2,pdns-domaininfo}.schema ; do echo include $schema ; done > ldap.conf
  - mkdir slapd.d
  - slaptest -f ldap.conf -F slapd.d
  - sudo cp slapd.d/cn=config/cn=schema/cn={*dns*.ldif /etc/ldap/slapd.d/cn=config/cn=schema/
  - sudo chown -R openldap:openldap /etc/ldap/slapd.d/
  - sudo service slapd restart
  - popd
  - sudo ldapmodify -Y EXTERNAL -H ldapi:/// -f ./modules/ldapbackend/testfiles/modify.ldif