language: cpp
compiler:
  - gcc
before_script:
 - sudo rm /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
 - sudo apt-get update
 - sudo apt-get install libboost-all-dev libtolua-dev bc libcdb-dev libnet-dns-perl unbound-host ldnsutils dnsutils bind9utils libtool libcdb-dev xmlto dblatex links asciidoc ruby-json ruby-sqlite3 rubygems libcurl4-openssl-dev ruby1.9.1 socat time libzmq1 libzmq-dev pkg-config
 - sudo update-alternatives --set ruby /usr/bin/ruby1.9.1
 - gem install bundler --no-rdoc --no-ri 
 - cd modules/remotebackend
 - ruby -S bundle install
 - cd ../..
script:
 - ./bootstrap
 - ./configure --with-modules='remote' --enable-unit-tests --enable-remotebackend-zeromq
 - make dist
 - make -j 4
 - make -j 4 check
 - cd ../../regression-tests
 - touch verify-dnssec-zone/allow-missing
 - ./start-test-stop 5300 remotebackend-zeromq
 - #./start-test-stop 5300 remotebackend-zeromq-dnssec
notifications:
  irc:
    channels:
      - "irc.oftc.net#powerdns-dev"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
