sudo: required
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
env:
  - PDNS_BUILD_PRODUCT=auth
  - PDNS_BUILD_PRODUCT=recursor
  - PDNS_BUILD_PRODUCT=dnsdist
  - PDNS_BUILD_PRODUCT=ixfrdist

cache:
  - pip

addons:
  apt:
    sources:
      - sourceline: 'ppa:jelu/validns'
      - sourceline: 'ppa:maxmind/ppa'
      - sourceline: 'ppa:zeha/libfstrm-ppa'
      - sourceline: 'deb [arch=amd64] http://repo.powerdns.com/ubuntu $(lsb_release -cs)-auth-master main'
        key_url: 'https://repo.powerdns.com/CBC8B383-pub.asc'
    packages:
      - alien
      - authbind
      - bind9utils
      - daemontools
      - default-jre
      - fakeroot
      - faketime
      - geoip-database
      - jq
      - ldap-utils
      - ldnsutils
      - libboost-all-dev
      - libcdb-dev
      - libedit-dev
      - libfaketime
      - libfstrm-dev
      - libgeoip-dev
      - libldap-dev
      - libluajit-5.1-dev
      - libmaxminddb-dev
      - libnet-dns-perl
      - libopendbx1-dev
      - libopendbx1-sqlite3
      - libp11-kit-dev
      - libprotobuf-dev
      - libsnmp-dev
      - libsodium-dev
      - libsodium18
      - libsqliteodbc
      - libyaml-cpp-dev
      - libzmq3-dev
      - lua-posix
      - moreutils
      - p11-kit
      - protobuf-compiler
      - ruby-json
      - rubygems-integration
      - slapd
      - snmpd
      - socat
      - softhsm
      - unbound-host
      - unixodbc-dev
      - validns

before_script:
  - git describe --always --dirty=+

  ### setup travis environment ###
  - sudo sysctl net.ipv6.conf.lo.disable_ipv6=0
  - export POSIXLY_CORRECT=1
  - export CFLAGS=-O0
  - export CXXFLAGS=-O0
  - export OPTFLAGS=-O0
  - sudo apt-get -qq update
  # you can remove this when updating dist to something newer than trusty
  - python -V 2>&1 |grep '2.7' >/dev/null || pyenv global 2.7
  # needed for virtualenv to use the pyenv python
  - pip install virtualenv

script:
  - ./build-scripts/travis.sh

notifications:
  irc:
    channels:
      - secure: "RDw5WKYf/gS3JnfIdkK51U4K2Xg/WNMn1uB/5AZbHbcqZJ/ZnbILCu0eBC83blQr+UuaQG7/sUFhWbtwoivD2I/4wOQGWIysBEZ8bSoySPSc4u0YU45aPjN+Ohrrp9qw7Smts3tYHbrOqfLfZ39L8lJq06vuMoBp6eHVkSBT7AY="
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
