language: cpp
compiler:
  - gcc
before_script:
 - git describe --always --dirty=+
 - sudo /sbin/ip addr add 10.0.3.0/24 dev lo
 - sudo /sbin/ip addr add 1.2.3.4/32 dev lo
 - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
 - sudo apt-get update -qq
 - sudo apt-get install --quiet --quiet --no-install-recommends
     alien
     authbind
     bc
     bind9utils
     daemontools
     dnsutils
     faketime
     geoip-database
     ldnsutils
     libboost-all-dev
     libbotan1.10-dev
     libcdb-dev
     libcdb-dev
     libcurl4-openssl-dev
     libgeoip-dev
     libldap2-dev
     liblua5.1-posix1
     libnet-dns-perl
     libopendbx1-dev
     libopendbx1-sqlite3
     libp11-kit-dev
     libtolua-dev
     libtool
     links
     moreutils
     p11-kit
     pkg-config
     python-virtualenv
     rpm
     ruby-json
     ruby-sqlite3
     ruby1.9.1
     rubygems
     socat
     softhsm
     time
     unbound-host
     xmlto
 - sudo sh -c 'sed s/precise/trusty/g /etc/apt/sources.list > /etc/apt/sources.list.d/trusty.list'
 - sudo apt-get update --quiet --quiet
 - sudo apt-get install --quiet --quiet liblmdb0 liblmdb-dev lmdb-utils libyaml-cpp-dev libzmq3-dev pandoc
 - sudo pip install pandoc==1.0.0-alpha.3 pandocfilters mkdocs==0.11.1 linkchecker==9.3
 - sudo update-alternatives --set ruby /usr/bin/ruby1.9.1
 - sudo touch /etc/authbind/byport/53
 - sudo chmod 755 /etc/authbind/byport/53
 - wget ftp://ftp.nominum.com/pub/nominum/dnsperf/2.0.0.0/dnsperf-2.0.0.0-1-rhel-6-x86_64.tar.gz
 - tar xzvf dnsperf-2.0.0.0-1-rhel-6-x86_64.tar.gz
 - fakeroot alien --to-deb dnsperf-2.0.0.0-1/dnsperf-2.0.0.0-1.el6.x86_64.rpm
 - sudo dpkg -i dnsperf_2.0.0.0-2_amd64.deb
 - travis_retry gem install bundler --no-rdoc --no-ri
 - sudo mkdir -p /etc/pkcs11/modules/
 - sudo cp -f regression-tests/softhsm.mod /etc/pkcs11/modules/softhsm
 - sudo cp -f regression-tests/softhsm.conf /etc/softhsm/softhsm.conf
 - sudo chmod 0755 /etc/softhsm/
 - sudo chmod 0644 /etc/softhsm/softhsm.conf
 - sudo chmod 0777 /var/lib/softhsm
 - p11-kit -l # ensure it's ok
script:
 - ./bootstrap
 - ./configure
     --with-dynmodules='bind geo geoip gmysql gpgsql gsqlite3 random'
     --with-modules=''
     --with-sqlite3
     --enable-botan1.10
     --enable-unit-tests
     --enable-tools
     --enable-experimental-ed25519
     --enable-experimental-pkcs11
     --disable-silent-rules
     --disable-dependency-tracking
 - make -k -j 4
 - cd regression-tests
 - touch tests/verify-dnssec-zone/allow-missing
 - touch tests/verify-dnssec-zone/skip.nsec3 # some (travis) tools in this test are unable to handle nsec3 zones
 - touch tests/verify-dnssec-zone/skip.optout
 - ./timestamp ./start-test-stop 5300 bind-dnssec-nsec3-both
notifications:
  irc:
    channels:
      - "irc.oftc.net#powerdns-dev"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
