language: cpp
compiler:
  - gcc
before_script:
 - git describe --always --dirty=+
 - sudo /sbin/ip addr add 10.0.3.0/24 dev lo
 - sudo /sbin/ip addr add 1.2.3.4/32 dev lo
 - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
 - sudo apt-get update -qq
 - sudo apt-get install --quiet --quiet --no-install-recommends
     alien
     authbind
     bc
     bind9utils
     daemontools
     dnsutils
     faketime
     geoip-database
     ldnsutils
     libboost-all-dev
     libbotan1.10-dev
     libcdb-dev
     libcdb-dev
     libcurl4-openssl-dev
     libgeoip-dev
     libldap2-dev
     liblua5.1-posix1
     libnet-dns-perl
     libopendbx1-dev
     libopendbx1-sqlite3
     libp11-kit-dev
     libtolua-dev
     libtool
     links
     moreutils
     p11-kit
     pkg-config
     python-virtualenv
     rpm
     ruby-json
     ruby-sqlite3
     ruby1.9.1
     rubygems
     socat
     softhsm
     time
     unbound-host
     xmlto
 - sudo sh -c 'sed s/precise/trusty/g /etc/apt/sources.list > /etc/apt/sources.list.d/trusty.list'
 - sudo apt-get update --quiet --quiet
 - sudo apt-get install --quiet --quiet liblmdb0 liblmdb-dev lmdb-utils libyaml-cpp-dev libzmq3-dev pandoc
script:
 - ./bootstrap
 - ./configure
     --with-dynmodules='bind gsqlite3'
     --with-modules=''
     --with-sqlite3
     --enable-botan1.10
     --enable-unit-tests
     --enable-tools
     --enable-experimental-ed25519
     --enable-experimental-pkcs11
     --disable-silent-rules
     --disable-dependency-tracking
 - make -k -j 4
 - cd regression-tests
 - touch tests/verify-dnssec-zone/allow-missing
 - touch tests/verify-dnssec-zone/skip.nsec3 # some (travis) tools in this test are unable to handle nsec3 zones
 - touch tests/verify-dnssec-zone/skip.optout
 - ./timestamp ./start-test-stop 5300 bind-dnssec-nsec3-both
notifications:
  irc:
    channels:
      - "irc.oftc.net#powerdns-dev"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
