version: 2.1

commands:
  auth-regress:
    description: "run one auth regression context"
    parameters:
      skip:
        type: string
        default: ""
      context:
        type: string
        default: ""
    steps:
      - run: |
          cd regression-tests
          [ -e ./vars ] && . ./vars
          rm -rf tests/*/skip
          for t in << parameters.skip >>
          do
            touch tests/$t/skip
          done
          ./start-test-stop 5300 << parameters.context >>

jobs:
  build-auth:
    docker:
      - image: debian:stretch
      - image: mcr.microsoft.com/mssql/server:2019-CTP2.2-ubuntu
        environment:
          - ACCEPT_EULA: Y
          - SA_PASSWORD: 'SAsa12%%'

    steps:
      - checkout

      - run:
          name: install dependencies
          command: ./build-scripts/circleci.sh debian-stretch-deps

      - run:
          name: autoconf
          command: autoreconf -vfi

      - run:
          name: configure
          command: ./configure --disable-lua-records --with-modules='bind gmysql godbc random'

      - run:
          name: build
          command: make -j3 -k

      - run:
          name: test gsqlite3 odbc
          command: ./build-scripts/circleci.sh configure-odbc-sqlite; cd regression-tests ; touch tests/verify-dnssec-zone/allow-missing ; GODBC_SQLITE3_DSN=pdns-sqlite3-1 ./start-test-stop 5300 godbc_sqlite3-nsec3

      - run:
          name: set up mssql odbc
          command: ./build-scripts/circleci.sh configure-odbc-mssql ; echo 'create database pdns' | isql -v pdns-mssql-docker-nodb sa SAsa12%%

      - run:
          name: set up mssql odbc testing
          command: |
            cd regression-tests
            echo 'export GODBC_MSSQL_PASSWORD=SAsa12%% GODBC_MSSQL_USERNAME=sa GODBC_MSSQL_DSN=pdns-mssql-docker' > ./vars

      - auth-regress:
          context: godbc_mssql-nodnssec
          skip: 8bit-txt-unescaped
      - auth-regress:
          context: godbc_mssql
          skip: 8bit-txt-unescaped
      - auth-regress:
          context: godbc_mssql-nsec3
          skip: 8bit-txt-unescaped
      - auth-regress:
          context: godbc_mssql-nsec3-optout
          skip: 8bit-txt-unescaped verify-dnssec-zone
      - auth-regress:
          context: godbc_mssql-nsec3-narrow
          skip: 8bit-txt-unescaped

  build-recursor:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get -qq --no-install-recommends install \
            autoconf \
            automake \
            ca-certificates \
            curl \
            bison \
            flex \
            g++ \
            git \
            libboost-all-dev \
            libcap-dev \
            libluajit-5.1-dev \
            libprotobuf-dev \
            libsodium-dev \
            libssl-dev \
            libsystemd-dev \
            libtool \
            make \
            pkg-config \
            protobuf-compiler \
            ragel \
            virtualenv
      - checkout
      - run:
          name: autoconf
          command: autoreconf -vfi
          working_directory: ~/project/pdns/recursordist
      - run:
          name: configure
          command: |
            CFLAGS="-O1 -Werror=vla" \
            CXXFLAGS="-O1 -Werror=vla" \
            ./configure \
            --enable-unit-tests \
            --prefix=/opt/pdns-recursor \
            --with-libsodium \
            --with-lua=luajit \
            --with-libcap \
            --with-protobuf=yes \
            --without-net-snmp
          working_directory: ~/project/pdns/recursordist
      - run:
          name: build
          command: make -j3 -k
          working_directory: ~/project/pdns/recursordist
      - run:
          name: make check
          command: make check
          working_directory: ~/project/pdns/recursordist

workflows:
  version: 2
  build-and-test-all:
    jobs:
      - build-auth
      - build-recursor
