version: 2.1

jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: install dependencies
          command: ./build-scripts/circleci.sh debian-stretch-deps

      - run:
          name: autoconf
          command: cd pdns/dnsdistdist && autoreconf -vfi

      - run:
          name: configure
          command: cd pdns/dnsdistdist && ./configure --enable-unit-tests --enable-dnstap --enable-dnscrypt --enable-dns-over-tls --enable-dns-over-https

      - run:
          name: build
          command: cd pdns/dnsdistdist && make -j3 -k

      - run:
          name: run tests
          command: cd regression-tests.dnsdist && DNSDISTBIN=../pdns/dnsdistdist/dnsdist ./runtests

