#!/usr/bin/env bash

set -e

if [ "$0" != "./build-scripts/dist-recursor" ]; then
  echo "Please run me from the root checkout dir"
  exit 1
fi

if [ -z "$VERSION" ]; then
  VERSION=$(./build-aux/gen-version)
  if [ -z "$VERSION" ]; then
    VERSION="UNKNOWN"
  fi
fi

set -x

cd pdns

ragel dnslabeltext.rl -o dnslabeltext.cc

cd ../docs
pandoc -s -t man manpages/pdns_recursor.1.md -o pdns_recursor.1
pandoc -s -t man manpages/rec_control.1.md -o rec_control.1
cd -

DIST_HOST="$(id -u -n)@$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo localhost)"

curl https://publicsuffix.org/list/public_suffix_list.dat > effective_tld_names.dat
./mkpubsuffixcc

DIRNAME=recursordist
rm -rf $DIRNAME
mkdir  $DIRNAME
cat >>$DIRNAME/config.h <<EOF
#define VERSION "$VERSION"
#define DIST_HOST "$DIST_HOST"
#define HAVE_BOOST 1
#define HAVE_MBEDTLS2 1
EOF
mkdir -p $DIRNAME/ext/rapidjson/include/rapidjson/internal
cp -a ../ext/rapidjson/include/rapidjson/*.h $DIRNAME/ext/rapidjson/include/rapidjson/
cp -a ../ext/rapidjson/include/rapidjson/internal/*.h $DIRNAME/ext/rapidjson/include/rapidjson/internal

echo '#include "../../../config.h"' > $DIRNAME/ext/yahttp/yahttp/yahttp-config.h
cp ../docs/pdns_recursor.1 ../docs/rec_control.1 $DIRNAME
cp configure-recursor $DIRNAME/configure
cp powerdns-example-script.lua $DIRNAME
mkdir -p $DIRNAME/contrib
cp ../contrib/systemd-pdns-recursor.service $DIRNAME/contrib
cp ../build-scripts/build-recursor-semistatic $DIRNAME/build-scripts
cp pdns-recursor.spec $DIRNAME

mkdir -p $DIRNAME/sysdeps
rm -f sysdeps-recursor/*~
cp  sysdeps-recursor/* $DIRNAME/sysdeps
touch $DIRNAME/dnslabeltext.cc # avoid spurious recompiles
tar cf $DIRNAME.tar $DIRNAME
bzip2 -f $DIRNAME.tar # .. solaris
