#!/bin/sh

set -x
pwd
mysqldiff

alias putil="$PDNSUTIL --config-dir=. --config-name=gmysql"

# add a record
putil add-record test.dyndns add-delete. A 127.0.0.108

# check if the record was added
mysqldiff 1 "Check if add-delete.test.dyndns. 3600 A 127.0.0.108 exists"

putil delete-rrset test.dyndns add-delete A

# check if the record was deleted
mysqldiff 2 "Check if record is gone" 1
