---
name: 'Build and test everything'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 22 * * 3'

jobs:
  build-auth:
    name: build auth
    runs-on: ubuntu-20.04
    env:
      UBSAN_OPTIONS: 'print_stacktrace=1:halt_on_error=1:suppressions=/home/runner/work/pdns/pdns/build-scripts/UBSan.supp'
      ASAN_OPTIONS: detect_leaks=0
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 5
          submodules: recursive
      - name: pwd
        run: pwd
      - name: env
        run: env
      - name: find
        run: find /home/runner -name 'UBSan.supp'
      - name: install clang
        run: sudo apt-get update && sudo apt-get --no-install-recommends install clang-11 llvm-11
      - name: install auth build deps
        run: |
          sudo apt-get update && sudo apt-get install -qq -y --no-install-recommends \
            autoconf \
            automake \
            bison \
            bzip2 \
            curl \
            default-libmysqlclient-dev \
            flex \
            g++ \
            git \
            libboost-all-dev \
            libcdb-dev \
            libcurl4-openssl-dev \
            libgeoip-dev \
            libkrb5-dev \
            libldap2-dev \
            liblmdb-dev \
            libluajit-5.1-dev \
            libmaxminddb-dev \
            libp11-kit-dev \
            libpq-dev \
            libsodium-dev \
            libsqlite3-dev \
            libssl-dev \
            libsystemd-dev \
            libtool \
            libyaml-cpp-dev \
            libzmq3-dev \
            make \
            pkg-config \
            python3-venv \
            ragel \
            ruby-bundler \
            sqlite3 \
            systemd \
            unixodbc-dev \
            wget
      - name: autoconf
        run: BUILDER_VERSION=0.0.0-git1 autoreconf -vfi
      - name: configure
        run: |
            CFLAGS="-O1 -Werror=vla -Werror=shadow -Wformat=2 -Werror=format-security -Werror=string-plus-int" \
            CXXFLAGS="-O1 -Werror=vla -Werror=shadow -Wformat=2 -Werror=format-security -Werror=string-plus-int -Wp,-D_GLIBCXX_ASSERTIONS" \
            ./configure \
              CC='clang-11' \
              CXX='clang++-11' \
              --enable-option-checking=fatal \
              --with-modules='bind geoip gmysql godbc gpgsql gsqlite3 ldap lmdb lua2 pipe random remote tinydns' \
              --enable-systemd \
              --enable-tools \
              --enable-unit-tests \
              --enable-backend-unit-tests \
              --enable-fuzz-targets \
              --enable-experimental-pkcs11 \
              --enable-remotebackend-zeromq \
              --with-lmdb=/usr \
              --with-libsodium \
              --prefix=/opt/pdns-auth \
              --enable-ixfrdist \
              --enable-asan \
              --enable-ubsan
      - name: show config.log
        if: ${{ failure() }}
        run: cat config.log
      - name: build
        run: make -j3 -k V=1
      # FIXME: save ccache here?
      - name: Install Ruby deps for remotebackend unit tests
        run: cd modules/remotebackend && ruby -S bundle install --path vendor/bundle
      - name: Run unit tests
        run: make check || (cat pdns/test-suite.log; false)
  build-recursor:
    name: build recursor
    runs-on: ubuntu-20.04
    env:
      UBSAN_OPTIONS: 'print_stacktrace=1:halt_on_error=1:suppressions=/home/runner/work/pdns/pdns/build-scripts/UBSan.supp'
      ASAN_OPTIONS: detect_leaks=0
    defaults:
      run:
        working-directory: ./pdns/recursordist/
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 5
          submodules: recursive
      - name: install clang
        run: sudo apt-get update && sudo apt-get --no-install-recommends install clang-11 llvm-11
      - name: install rec build deps
        run: |
          sudo apt-get update && sudo apt-get install -qq -y --no-install-recommends \
            autoconf \
            automake \
            ca-certificates \
            curl \
            bison \
            flex \
            g++ \
            git \
            libboost-all-dev \
            libcap-dev \
            libluajit-5.1-dev \
            libfstrm-dev \
            libsnmp-dev \
            libsodium-dev \
            libssl-dev \
            libsystemd-dev \
            libtool \
            make \
            pkg-config \
            ragel \
            systemd \
            python3-venv
      - name: autoconf
        run: BUILDER_VERSION=0.0.0-git1 autoreconf -vfi
      - name: configure
        run: |
            CFLAGS="-O1 -Werror=vla -Werror=shadow -Wformat=2 -Werror=format-security -Werror=string-plus-int" \
            CXXFLAGS="-O1 -Werror=vla -Werror=shadow -Wformat=2 -Werror=format-security -Werror=string-plus-int -Wp,-D_GLIBCXX_ASSERTIONS" \
            ./configure \
              CC='clang-11' \
              CXX='clang++-11' \
              --enable-option-checking=fatal \
              --enable-unit-tests \
              --enable-nod \
              --enable-systemd \
              --prefix=/opt/pdns-recursor \
              --with-libsodium \
              --with-lua=luajit \
              --with-libcap \
              --with-net-snmp \
              --enable-dns-over-tls \
              --enable-asan \
              --enable-ubsan
      - name: show config.log
        if: ${{ failure() }}
        run: cat config.log
      - name: build
        run: make -j3 -k V=1
      # FIXME: save ccache here?
      - name: Run unit tests
        run: make check || (cat pdns/test-suite.log; false)
